dateFormat:
  full: "dd.MM.yyyy hh:mm:ss" # see https://www.w3schools.com/java/java_date.asp

messages:
  # Please avoid modifying the messages too much (especially the errors) so they can be understood by you and other admins
  # To disable a message leave a blank "" (avoid doing this)
  apiConnecting: "&7Querying MojangAPI, please wait..."
  error:
    api:
      playerCantGet: "Player not found in the Mojang API or no internet connection."
    invalid:
      uuid: "&cNot a valid UUID."
      username: "&cNot a valid username."
    unspecified:
      player: "&cNo player username or UUID specified."
      username: "&cNo player username specified."
      uuid: "&cNo player UUID specified."
    general: "&cAn error occurred. See console for details."
    playerCantGet: "&cFailed to get player."
    noPermission: "&cAccess denied."