name: PlayerDataManager
version: '${project.version}'
main: com.wolfyxon.playerdatamgr.PlayerDataMgr
api-version: 1.19
authors: [ Wolfyxon ]
description: All in one plugin for checking and managing players' data even if they are not online. Useful on non-premium servers and with shulker/book bans
commands:
  getuuid:
    description: player's UUID (also works in offline mode)
    usage: /<command> <player>
    permission: playerdatamgr.commands.getuuid
    aliases: [uuid,getuuid]
  seen:
    description: Checks when a player was last online (UUID can be used instead of username)
    usage: /<command> <player>
    permission: playerdatamgr.commands.seen
    aliases: [seen,lastonline]
  firstjoined:
    description: Checks when was the first time a player has joined (UUID can be used instead of username)
    usage: /<command> <player>
    permission: playerdatamgr.commands.firstjoined
    aliases: [firstjoined,firstplayed,playedforthefirsttime,joinedforthefirsttime]
  playerdata:
    description: Main command. Used for reading, modyfying and removing data
    usage: /<command> <action>
    permission: playerdatamgr.commands.main
    aliases: [playerdata,playerdatamanager]