name: PlayerDataManager
version: '${project.version}'
main: com.wolfyxon.playerdatamgr.PlayerDataMgr
api-version: 1.19
authors: [ Wolfyxon ]
description: A plugin that allows you to find and modify players' data such as inventories without dealing with .dat files
commands:
  getuuid:
    description: player's UUID (also works in offline mode)
    usage: /<command> <player>
    permission: playerdatamgr.uuid
    aliases: [uuid,getuuid]
