name: PlayerDataManager
version: '${project.version}'
main: com.wolfyxon.playerdatamgr.PlayerDataMgr
api-version: 1.19
authors: [ Wolfyxon ]
description: A plugin that allows you to find and modify players' data such as inventories without dealing with .dat files
commands:
  getuuid:
    description: player's UUID (also works in offline mode)
    usage: /<command> <player>
    permission: playerdatamgr.getuuid
    aliases: [uuid,getuuid]
  seen:
    description: Checks when a player was last online (UUID can be used instead of username)
    usage: /<command> <player>
    permission: playerdatamgr.seen
    aliases: [seen,lastonline]