name: PlayerDataManager
version: '${project.version}'
main: com.wolfyxon.playerdatamgr.PlayerDataMgr
api-version: 1.19
authors: [ Wolfyxon ]
description: All in one plugin for checking and managing players' data even if they are not online. Useful on non-premium servers and with shulker/book bans
commands:
  playerdata:
    description: Main command. Used for reading, modyfying and removing data
    usage: /<command> <action>
    aliases: [ playerdata ]
  getuuid:
    description: Gets UUID from player. Works on both offline and online mode servers.
    usage: /<command> <player>
    permission: playerdatamgr.commands.uuid
    aliases: [uuid,uuid]
  getonlineuuid:
    description: Gets player's UUID from the MojangAPI using username. Use only in online mode servers.
    usage: /<command> <player>
    permission: playerdatamgr.commands.uuid
    aliases: [onlineuuid,onlineuuid]
  getofflineuuid:
    description: Gets offline player's UUID. Use only in offline mode servers.
    usage: /<command> <player>
    permission: playerdatamgr.commands.uuid
    aliases: [ offlineuuid,offlineuuid ]
  seen:
    description: Checks when a player was last online (UUID can be used instead of username)
    usage: /<command> <player>
    permission: playerdatamgr.commands.seen
    aliases: [seen,lastonline]
  firstjoined:
    description: Checks when was the first time a player has joined (UUID can be used instead of username)
    usage: /<command> <player>
    permission: playerdatamgr.commands.firstjoined
    aliases: [firstjoined,firstplayed]
